// www-vue/src/components/VehicleGauge.vue
<template>
	<div>
		<div class="container">
			<div class="row">
				<div class="col-sm-2" />
				<div class="col-sm-3">
			    	<canvas data-type="radial-gauge"
					data-title="SOC"
					data-minValue="0"
					data-maxValue="150"
					:data-value="vehicle.speed"   
					data-valueInt="3"
					data-valueDec="0"
					data-width="200" />
				</div>
				<div class="col-sm-2" />
				<div class="col-sm-3">
			    	<canvas data-type="radial-gauge"
					data-title="MPH"
					data-minValue="0"
					data-maxValue="100"
					:data-value="vehicle.speed"   
					data-valueInt="3"
					data-valueDec="0"
					data-width="200" />
				</div>
				<div class="col-sm-2" />
			</div>
		</div>
	</div>
</template>

<script>
import RadialGauge from 'canvas-gauges';

export default {
	name: "vehicle-gauge",
	props: {
		vehicle: {
			type: Object
		}
	}
}
</script>

// www-dev/src/hams/components/VehicleGauge.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import RadialGauge from 'canvas-gauges';

export default class VehicleGauge extends React.Component {
  render () {
    return (
    	<div className="container">
    		<div className="row">
    			<div className="col-sm-2" />
    			<div className="col-sm-3">
			    	<canvas data-type="radial-gauge"
					data-title="SOC"
					data-minValue="0"
					data-maxValue="100"
					data-value={this.props.vehicle.soc}   
					data-valueInt="3"
					data-valueDec="0"
					data-width="200" />
				</div>
				<div className="col-sm-2" />
				<div className="col-sm-3">
			    	<canvas data-type="radial-gauge"
					data-title="MPH"
					data-minValue="0"
					data-maxValue="150"
					data-value={this.props.vehicle.speed}   
					data-valueInt="3"
					data-valueDec="0"
					data-width="200" />
				</div>
				<div className="col-sm-2" />
			</div>
		</div>
	);
  }
}
